apiVersion: v1
kind: Config
clusters:
- name: my-eks-cluster
  cluster:
    server: https://ae7fb945522df1404f4fe8b9e0abdae6.gr7.us-east-2.eks.amazonaws.com/
    certificate-authority-data: base64decode(data.aws_eks_cluster.tg-tekton-eks-cluster.certificate_authority[0].data)
contexts:
- name: my-eks-context
  context:
    cluster: my-eks-cluster
    user: my-eks-user
current-context: my-eks-context
users:
- name: my-eks-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - eks
        - get-token
        - --region
        - us-east-2
        - --cluster-name
        - tg-tekton-eks-cluster
