apiVersion: v1
kind: Config
clusters:
- name: my-eks-cluster
  cluster:
    server: https://6A3CA31C256A97BCE777AF85236D9AAE.gr7.us-east-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1ERXlOVEV3TVRZeE0xb1hEVE14TURFeU16RXdNVFl4TTFvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTUp6CkpzV2trY1JBS3B3RExGbzBLTkZsZEhJV05OOUVNd2daVWdna2RoSXRMTThHRzhmUzg1QWp2UEcrMllzVFdWeSsKOGphNGtTbUZoRHNNMWNkZXJOTUtQcmZSellJR0szaVBBSWFKRThXWkpUYWpybytOeU9pdUxNYnh4ZTMweTFaMAplL0xyWVk4QjRVZjVUMXBYaEhQWE5ybmdDRksyQnJjY3lHUmRZQnd4SUNDT3lMYU1nWGdPWlgvSUE2WmxEUEJDCnp2WERPS0dIbE1Zek9TaHNLVDRNVU1wdzZPdFFVeHNoQjVtWE5teVRtb1dkOTNiZzZURGF0ZGhQU1hZRVEzd20KWHQyRmFrN2pzc3ovRktzTEtkK3FMcUwvZXVhUmN2a1d5T0NEMEVuelJvQVFkT28ydXJ1S25wRTE2eTRJVXM0VQpSbjlMa2c3UzF0Q0dYdUdWTjVFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFKbG84ZUlUMlJpOVZhckFGSkpxWC9rUnB6UmMKcG9YeHZqdzhnTE41WjA2emJtd01NM2h4bWlWVVJFZGd2b3lvQlYyeUl0RW55VmxYckc1M3cvc1pwMHpnRzY0VgpxTjRGMmY5Z252c3F0Z0w3d0VnQUh3Wko0clhoVDYyeGd1dHFneGo5SXl2WHZjQjh0UDFMeXBhQ3FuWENkN2I0CnVVWVd4TVlUc3dVamhhc0VDdTBmTXFyRjZIWGJTYVJJT2ZPVHFLQWU5WjJ3QU5QaHN5aWszMGVOWHBpSVUvYngKVHJxVUlhVExlcDZhNGQvSzJyWlhrVitNcTFuUGVHejFkQU5hTnQ3TXAzZXMwbVl6eDNSSkkwcmhxdFNxV1QvbwplQ0xpVkhnb1RiK2NtUmtnT3Y2cUtsRkV6aHN6RThQZ041aTVnU3B5K3FjSUtkV2NZemZVVUwrQWYrND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
contexts:
- name: my-eks-context
  context:
    cluster: my-eks-cluster
    user: my-eks-user
current-context: my-eks-context
users:
- name: my-eks-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - eks
        - get-token
        - --region
        - us-east-1
        - --cluster-name
        - eks-secure
